<?php
/**
 * Created by PhpStorm.
 * User: web jinxiu89@163.com
 * Date: 2019-05-18
 * Time: 11:12
 * 命名规范：文件名首字母大写
 * 类 首写字母大写
 * 函数 驼峰命名  如getInfo
 */
namespace app\admin\controller;

use app\common\logic\Aboutme as Logic;
use think\App;

class Aboutme extends Base
{
    public function __construct(App $app = null)
    {
        parent::__construct($app);
    }
    public function initialize()
    {
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
            $aboutme = model('Aboutme')->getAboutmeThumbnail();
            $this->assign([
                'aboutme'=>$aboutme['data']
            ]);
            return $this->fetch();
    }
    public function aboutmeModify(){
        if (request()->isPost()){
            $data = input('post.');
            //dump($data);exit();
            $status = (new Logic())->aboutmeModify($data);
            return $status;
        }else{
            $aboutme = model('Aboutme')->getAboutmeThumbnail();
            $this->assign([
                'aboutme'=>$aboutme['data']
            ]);
            return $this->fetch();
        }
    }
}
