<?php
/**
 * Created by PhpStorm.
 * User: web jinxiu89@163.com
 * Date: 2019-05-18
 * Time: 11:12
 * 命名规范：文件名首字母大写
 * 类 首写字母大写
 * 函数 驼峰命名  如getInfo
 */
namespace app\admin\controller;


use app\common\logic\System as System;
use app\common\logic\Article as Article;
use think\Controller;
use think\exception\ValidateException;

class Base extends Controller
{
    /**
     * 检验登陆状态
     * @var    obj    $session  全局初始化获取登陆状态,未经登录不允许访问任何文件
     * @var    obj    $logicsystem  全局初始化栏目列表
     * @var    obj    $artcat  文章分类
     */
    protected $session;
    protected $logicsystem;
    public function initialize()
    {
        parent::initialize();
        $this->session=session('admin','','admin');

        if(!$this->session){
            return $this->error('您还没有登录，请先登录','/admin/login');
        }
        $this->logicsystem=new System();
        $basesyscat = $this->logicsystem->getSystemCategory();
        $artcat = (new Article())->getArticleCategory();
        
        $this->assign([
            'admin'=>$this->session,
            'basesyscat'=>$basesyscat[0],
            'artcat'=>$artcat,
        ]);
        //parent::initialize(); // TODO: Change the autogenerated stub
    }



}
