<?php
/**
 * Created by PhpStorm.
 * User: web jinxiu89@163.com
 * Date: 2019-05-18
 * Time: 11:12
 * 命名规范：文件名首字母大写
 * 类 首写字母大写
 * 函数 驼峰命名  如getInfo
 */
namespace app\admin\controller;

use app\common\logic\Login as Logic;



class Login extends Base
{
    /**
     * 登录页面需要终止全局不存在$session情况下的跳转，需要重写初始化initialize
    */
    public function initialize()
    {
        $this->session=session('admin','','admin');
        //parent::initialize(); // TODO: Change the autogenerated stub
    }




    public function login(){
        //如果是登录操作
        if (request()->isPost()){
            //获取用户输入的数据
            $data = input('post.');
            //dump(!$data['online']);exit();
            //通过逻辑层进行数据比对，成功则登录
            $status = (new Logic())->adminLogin($data);
            if ($status['status']==false){
                return $this->error($status['message']);
            }else{
                session('admin',$status['data'],'admin');
                return $this->success($status['message'],'/admin');
            }
        }
        //如果用户已经登录，直接进入后台
        elseif($this->session){
                return $this->success('您已登录，现在为您跳转','/admin');
        }else{
                return $this->fetch();
        }
    }
    //用户推出
    public function loginOut(){
        $this->session= session(null,'','admin');
        return $this->redirect('/admin/login');
    }
}
