<?php
/**
 * Created by PhpStorm.
 * User: web jinxiu89@163.com
 * Date: 2019-05-18
 * Time: 11:12
 * 命名规范：文件名首字母大写
 * 类 首写字母大写
 * 函数 驼峰命名  如getInfo
 */
namespace app\index\controller;


use app\common\logic\System as System;
use app\common\logic\Article as Article;
use think\Controller;
use think\exception\ValidateException;

class Base extends Controller
{
    /**
     * @var    obj    $artcat  文章分类
     * @var    obj    $basesyscat  栏目分类
     * @var    obj    $aboutme  关于我
     * @var
     */
    protected $logicsystem;
    public function initialize()
    {
        $this->logicsystem=new System();
        $basesyscat = $this->logicsystem->getSystemCategory();
        $artcat = (new Article())->getArticleCategory();
        $aboutme = model('Aboutme')->getAboutmeThumbnail();
        $this->assign([
            'basesyscat'=>$basesyscat[0],
            'artcat'=>$artcat,
            'aboutme'=>$aboutme['data']
        ]);
        //parent::initialize(); // TODO: Change the autogenerated stub
    }



}
